# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

# Upload a .tar file (adjust the path to a real .tar on your machine)
POST http://127.0.0.1:8000/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="sample.tar"
Content-Type: application/x-tar

< ./sample.tar
--boundary--

###
