"""add extracted_json_path to courses

Revision ID: b0efcfc5ef9a
Revises: d96b7799ed30
Create Date: 2026-06-22 17:43:32.075985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0efcfc5ef9a'
down_revision: Union[str, Sequence[str], None] = 'd96b7799ed30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('extracted_json_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'extracted_json_path')
    # ### end Alembic commands ###
